---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-hoprd-{{ clusterNodes }}-{{ workloadName }}
  namespace: k6-operator-system
spec:
  parallelism: 1
  script:
    localFile: /app/hoprnet/{{ testName }}-test.js
  separate: true
  arguments: --tag testid={{ testid }} --summary-export=/test-results/k6/test-execution-$(date +%Y%m%d-%H%M%S).json
  runner:
    image: europe-west3-docker.pkg.dev/hoprassociation/docker-images/hoprd-k6:latest
    securityContext:
      runAsUser: 0
    resources:
      limits:
        cpu: 3
        memory: 3Gi
      requests:
        cpu: 3
        memory: 3Gi
    env:
      - name: K6_CLUSTER_NODES
        value: {{ clusterNodes }}
      - name: K6_TOPOLOGY_NAME
        value: {{ topologyName }}
      - name: K6_WORKLOAD_NAME
        value: {{ workloadName }}
      - name: K6_HOPS
        value: "{{ hops }}"
      - name: K6_REQUESTS_PER_SECOND_PER_VU
        value: "{{ requestsPerSecondPerVu }}"
      - name: K6_TEST_DURATION
        value: "{{ duration }}"
      - name: K6_ITERATION_TIMEOUT
        value: "{{ iterationTimeout }}"
      - name: K6_VU_PER_ROUTE
        value: "{{ vuPerRoute }}"
      - name: K6_PAYLOAD_SIZE
        value: "1048576"
      - name: K6_DOWNLOAD_THROUGHPUT
        value: "524288"
      - name: K6_UPLOAD_THROUGHPUT
        value: "1048576"
      - name: K6_DOWNLOAD_SEGMENT_SIZE
        value: "1400"
      - name: K6_UPLOAD_SEGMENT_SIZE
        value: "1400"
      - name: K6_SKIP_HOPRD_SESSIONS
        value: "false"
      - name: K6_ECHO_SERVERS_REPLICAS
        value: "4"
      - name: HOPRD_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: hoprd-api-tokens
            key: {{ clusterNodes }}
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: http://kube-prometheus-stack-prometheus.monitoring.svc:9090/api/v1/write
      - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
        value: 'true'
      - name: K6_OUT
        value: xk6-prometheus-rw
    volumes:
      - name: test-results
        persistentVolumeClaim:
          claimName: test-results
    volumeMounts:
      - name: test-results
        mountPath: /test-results/k6
