---
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: "{{ clusterNodes }}-{{ workloadName }}"
  namespace: k6-operator-system
spec:
  parallelism: 1
  script:
    localFile: /app/hoprnet/{{ testScript }}-test.js
  separate: true
  arguments: --tag testid={{ executionName }} --no-thresholds --summary-export=/app/hoprnet/test-execution-$(date +%Y%m%d-%H%M%S).json
  runner:
    image: europe-west3-docker.pkg.dev/hoprassociation/docker-images/hoprd-k6:latest
    securityContext:
      runAsUser: 0
    resources:
      limits:
        cpu: 3
        memory: 3Gi
      requests:
        cpu: 3
        memory: 3Gi
    env:
      - name: HOPRD_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: hoprd-api-tokens
            key: "{{ clusterNodes }}"
      - name: K6_EXECUTION_NAME
        value: "{{ executionName }}"
      - name: K6_CLUSTER_NODES
        value: "{{ clusterNodes }}"
      - name: K6_TOPOLOGY_NAME
        value: "{{ topologyName }}"
      - name: K6_WORKLOAD_NAME
        value: "{{ workloadName }}"
      - name: K6_SKIP_HOPRD_SESSIONS
        value: "{{ skipHoprdSessions }}"
      - name: K6_SKIP_SCENARIO_DOWNLOAD
        value: "{{ skipScenarioDownload }}"
      - name: K6_SKIP_SCENARIO_UPLOAD
        value: "{{ skipScenarioUpload }}"
      - name: K6_SESSION_CAPABILITIES
        value: "{{ sessionCapabilities }}"
      - name: K6_SESSION_MAX_SURB_UPSTREAM
        value: "{{ sessionMaxSurbUpstream }}"
      - name: K6_SESSION_RESPONSE_BUFFER
        value: "{{ sessionResponseBuffer }}"
      - name: K6_ECHO_SERVERS_REPLICAS
        value: "{{ echoServersReplicas }}"
      - name: K6_TEST_DURATION
        value: "{{ duration }}"
      - name: K6_ITERATION_TIMEOUT
        value: "{{ iterationTimeout }}"
      - name: K6_VU_PER_ROUTE
        value: "{{ vuPerRoute }}"
      - name: K6_PAYLOAD_SIZE
        value: "{{ payloadSize }}"
      - name: K6_DOWNLOAD_THROUGHPUT
        value: "{{ downloadThroughput }}"
      - name: K6_UPLOAD_THROUGHPUT
        value: "{{ uploadThroughput }}"
      - name: K6_RUNNER_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: http://kube-prometheus-stack-prometheus.monitoring.svc:9090/api/v1/write
      - name: K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM
        value: 'true'
      - name: K6_OUT
        value: xk6-prometheus-rw
      - name: K6_REQUESTS_PER_SECOND_PER_VU
        value: "{{ requestsPerSecondPerVu }}"
