---
name: Build Docker

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
concurrency:
  group: k6
  cancel-in-progress: true

jobs:

  build:
    name: docker
    runs-on: self-hosted-hoprnet-small
    steps:
      - name: Checkout hoprnet repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud Credentials
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}

      - name: Login Google Container Registry
        uses: docker/login-action@v2
        with:
          registry: europe-west3-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: kubernetes

      - name: Get docker tag
        id: vars
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "TAG=pr-${{ github.event.pull_request.number }}" | tee -a $GITHUB_OUTPUT
          else
            echo "TAG=latest" | tee -a $GITHUB_OUTPUT
          fi

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: k6
          tags: europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images/hoprd-k6:${{ steps.vars.outputs.TAG }}
  